// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmunomwuhhrdttxnztkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdW5vbXd1aGhyZHR0eG56dGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTkwOTIsImV4cCI6MjA3MDgzNTA5Mn0.ydj7tLoRdXO6PPm9L7pQZ0BAPOpPtZOs3GnLh_ujwpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});